export const GET_ERRORS = 'GET_ERRORS';
export const NO_ERRORS = 'NO_ERRORS';

export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const REGISTER_COMPANY_FAIL = 'REGISTER_COMPANY_FAIL';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
