export const GET_ERRORS = 'GET_ERRORS';
export const NO_ERRORS = 'NO_ERRORS';

// authentication
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const REGISTER_COMPANY_FAIL = 'REGISTER_COMPANY_FAIL';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_DEFAULT = 'LOGIN_DEFAULT'
export const CREATE_DIETICIAN_SUCCESS = 'CREATE_DIETICIAN_SUCCESS';
export const CREATE_DIETICIAN_FAIL = 'CREATE_DIETICIAN_SUCCESS';
export const CREATE_DIETICIAN_DEFAULT = 'CREATE_DIETICIAN_DEFAULT';
export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAIL = 'CREATE_PATIENT_FAIL';

export const UPDATE_COMPANY_DATA = 'UPDATE_COMPANY_DATA';
export const GET_ALL_ADMINS = 'GET_ALL_ADMINS';
export const DELETE_USER = 'DELETE_USER';

//patients
export const GET_ALL_PATIENTS = 'GET_ALL_PATIENTS';
export const EDIT_PATIENT = 'EDIT_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';


// dietitian
export const GET_ALL_DIETICIANS = 'GET_ALL_DIETICIANS';
export const GET_DIETITIAN = 'GET_DIETITIAN';
export const UPDATE_DIETITIAN_DATA = 'UPDATE_DIETITIAN_DATA';

